name: ci
on: [push, pull_request]
jobs:
    test:
        runs-on: ubuntu-latest
        strategy:
            matrix: { python-version: ["3.10", "3.11", "3.12"] }
        steps:
            - uses: actions/checkout@v4
            - uses: actions/setup-python@v5
              with:
                  python-version: ${{ matrix.python-version }}
            - run: uv pip install -e ".[all]"
            - run: uv run ruff check .
            - run: uv run pytest -q --cov=nlp_toolkit
